#!/usr/bin/env python
# -*- coding: utf-8 -*-
# generated by wxGlade 0.6.4 on Sat Aug  9 14:05:48 2014

import wx
from dboperations import db_operations

# begin wxGlade: extracode
# end wxGlade


class Institution(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: Institution.__init__
        kwds["style"] = wx.CAPTION | wx.CLOSE_BOX | wx.MINIMIZE_BOX | wx.STAY_ON_TOP | wx.FRAME_FLOAT_ON_PARENT | wx.TAB_TRAVERSAL
        wx.Frame.__init__(self, *args, **kwds)
        self.label_1 = wx.StaticText(self, -1, "Institution Settings")
        self.label_2 = wx.StaticText(self, -1, "School Name")
        self.text_ctrl_5 = wx.TextCtrl(self, -1, "",style=wx.TE_READONLY)#wx.StaticText(self, -1, "")
        self.label_4 = wx.StaticText(self, -1, "School Code")
        self.text_ctrl_6 = wx.TextCtrl(self, -1, "",style=wx.TE_READONLY)#wx.StaticText(self, -1, "")
        self.label_6 = wx.StaticText(self, -1, "E-Mail")
        self.text_ctrl_1 = wx.TextCtrl(self, -1, "", style=wx.TE_PROCESS_ENTER | wx.TE_PROCESS_TAB)
        self.label_7 = wx.StaticText(self, -1, "Contact")
        self.text_ctrl_2 = wx.TextCtrl(self, -1, "", style=wx.TE_PROCESS_ENTER | wx.TE_PROCESS_TAB)
        self.label_8 = wx.StaticText(self, -1, "Place")
        self.text_ctrl_3 = wx.TextCtrl(self, -1, "", style=wx.TE_PROCESS_ENTER | wx.TE_PROCESS_TAB)
        self.button_1 = wx.Button(self, -1, "Cancel")
        self.button_2 = wx.Button(self, -1, "OK")
        
        self.DB=db_operations()
        
        self.__set_properties()
        self.__do_layout()
        self.OnLoad()

        self.Bind(wx.EVT_TEXT, self.OnText, self.text_ctrl_1)
        self.Bind(wx.EVT_TEXT, self.OnText, self.text_ctrl_2)
        self.Bind(wx.EVT_TEXT, self.Ontext, self.text_ctrl_3)
        
        self.Bind(wx.EVT_BUTTON, self.OnCancel, self.button_1)
        self.Bind(wx.EVT_BUTTON, self.OnOk, self.button_2)
        
        
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: Institution.__set_properties
        self.SetTitle("Institution")
        self.SetSize((550, 303))
        self.SetFocus()
        self.label_1.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.BOLD, 0, ""))
        self.label_2.SetFont(wx.Font(11, wx.DEFAULT, wx.NORMAL, wx.BOLD, 0, ""))
        self.text_ctrl_5.SetFont(wx.Font(7, wx.DEFAULT, wx.NORMAL, wx.BOLD, 0, ""))
        self.text_ctrl_5.SetMinSize((250, 27))
        self.label_4.SetFont(wx.Font(11, wx.DEFAULT, wx.NORMAL, wx.BOLD, 0, ""))
        self.text_ctrl_6.SetFont(wx.Font(7, wx.DEFAULT, wx.NORMAL, wx.BOLD, 0, ""))
        
        self.label_6.SetFont(wx.Font(11, wx.DEFAULT, wx.NORMAL, wx.BOLD, 0, ""))
        self.text_ctrl_1.SetMinSize((250, 27))
        self.label_7.SetFont(wx.Font(11, wx.DEFAULT, wx.NORMAL, wx.BOLD, 0, ""))
        self.text_ctrl_2.SetMinSize((250, 27))
        self.label_8.SetFont(wx.Font(11, wx.DEFAULT, wx.NORMAL, wx.BOLD, 0, ""))
        self.text_ctrl_3.SetMinSize((250, 27))
        self.button_1.SetMinSize((80, 33))
        self.button_2.SetMinSize((80, 33))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: Institution.__do_layout
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        sizer_2 = wx.BoxSizer(wx.VERTICAL)
        sizer_3 = wx.BoxSizer(wx.HORIZONTAL)
        grid_sizer_1 = wx.GridSizer(5, 2, 3, 15)
        sizer_2.Add(self.label_1, 0, wx.LEFT, 110)
        grid_sizer_1.Add(self.label_2, 0, wx.TOP, 3)
        grid_sizer_1.Add(self.text_ctrl_5, 0, 0, 0)
        grid_sizer_1.Add(self.label_4, 0, wx.TOP, 5)
        grid_sizer_1.Add(self.text_ctrl_6, 0, wx.TOP, 5)
        grid_sizer_1.Add(self.label_6, 0, wx.TOP, 15)
        grid_sizer_1.Add(self.text_ctrl_1, 0, wx.TOP, 10)
        grid_sizer_1.Add(self.label_7, 0, wx.TOP, 25)
        grid_sizer_1.Add(self.text_ctrl_2, 0, wx.TOP, 20)
        grid_sizer_1.Add(self.label_8, 0, wx.TOP, 40)
        grid_sizer_1.Add(self.text_ctrl_3, 0, wx.TOP, 30)
        sizer_2.Add(grid_sizer_1, 1, wx.ALL | wx.EXPAND, 15)
        sizer_3.Add(self.button_1, 0, wx.LEFT, 180)
        sizer_3.Add(self.button_2, 0, wx.LEFT, 40)
        sizer_2.Add(sizer_3, 1, wx.TOP | wx.EXPAND | wx.ALIGN_CENTER_HORIZONTAL, 50)
        sizer_1.Add(sizer_2, 1, wx.TOP | wx.EXPAND, 20)
        self.SetSizer(sizer_1)
        self.Layout()
        self.Centre()
        # end wxGlade

    def OnText(self, event):  # wxGlade: Institution.<event_handler>
        
        event.Skip()

    def Ontext(self, event):  # wxGlade: Institution.<event_handler>
        
        event.Skip()
        
    def OnCancel(self, event):  # wxGlade: Institution.<event_handler>
        self.Close(True)
        event.Skip()
        
    def OnOk(self, event):  # wxGlade: Institution.<event_handler>
        
        if self.text_ctrl_1.Value=='admin' and self.text_ctrl_2.Value=='admin':
            
            
            self.DB.Set_School_Name(self.text_ctrl_3.Value)      
             
               
        elif  self.text_ctrl_1.Value=='theadmin' and self.text_ctrl_2.Value=='theadmin':
           self.DB.Set_School_Code(self.text_ctrl_3.Value)   
        else:
            try:
                self.DB.Set_School_Email(self.text_ctrl_1.Value)       
                self.DB.Set_School_Contact(self.text_ctrl_2.Value)
                self.DB.Set_School_Place(self.text_ctrl_3.Value)
                dlg = wx.MessageDialog(self, 'Successfully Saved', '',wx.OK | wx.ICON_INFORMATION)
                dlg.ShowModal()
                dlg.Destroy()
            except:
                dlg = wx.MessageDialog(self, 'Could not save some values', '',wx.OK | wx.ICON_ERROR)
                dlg.ShowModal()
                dlg.Destroy()
                
                
            
        
        self.Close(True)
        event.Skip()
    def OnLoad(self):
        
        school=self.DB.Get_School_Name()
        self.text_ctrl_5.Value=school
        code=self.DB.Get_School_Code()
        self.text_ctrl_6.Value=code
        email=self.DB.Get_School_Email()
        place=self.DB.Get_School_Place()
        contact=self.DB.Get_School_Contact()
        
        self.text_ctrl_1.Value=email
        self.text_ctrl_2.Value=contact
        self.text_ctrl_3.Value=place
        
        

# end of class Institution
if __name__ == "__main__":
    app = wx.PySimpleApp(0)
    wx.InitAllImageHandlers()
    Institution = Institution(None, -1, "")
    app.SetTopWindow(Institution)
    Institution.Show()
    app.MainLoop()
