#!/usr/bin/env python
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 0.6.8 on Wed Sep  7 01:01:52 2016
#

import wx

# begin wxGlade: dependencies
import gettext
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class student_profie(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: student_profie.__init__
        kwds["style"] = wx.CAPTION | wx.CLOSE_BOX | wx.MINIMIZE_BOX | wx.MAXIMIZE | wx.MAXIMIZE_BOX | wx.SYSTEM_MENU | wx.RESIZE_BORDER | wx.CLIP_CHILDREN
        wx.Frame.__init__(self, *args, **kwds)
        self.panel_1 = wx.Panel(self, wx.ID_ANY, style=wx.RAISED_BORDER | wx.TAB_TRAVERSAL)
        self.combo_box_13 = wx.ComboBox(self.panel_1, wx.ID_ANY, choices=[], style=wx.CB_DROPDOWN)
        self.combo_box_14 = wx.ComboBox(self.panel_1, wx.ID_ANY, choices=[], style=wx.CB_DROPDOWN)
        self.combo_box_15 = wx.ComboBox(self.panel_1, wx.ID_ANY, choices=[], style=wx.CB_DROPDOWN)
        self.button_1 = wx.Button(self.panel_1, wx.ID_ANY, _("Add New"))
        self.text_ctrl_1 = wx.TextCtrl(self.panel_1, wx.ID_ANY, "", style=wx.TE_PROCESS_ENTER | wx.TE_CENTRE)
        self.bitmap_button_2 = wx.BitmapButton(self.panel_1, wx.ID_ANY, wx.Bitmap("/media/ghssvythiri/10C63D64C63D4AEC/asif/sqlite_working_aug_16/Resources/img/pass.jpg", wx.BITMAP_TYPE_ANY), style=wx.BU_AUTODRAW)
        self.static_line_1 = wx.StaticLine(self.panel_1, wx.ID_ANY)
        self.bitmap_button_1 = wx.BitmapButton(self.panel_1, wx.ID_ANY, wx.Bitmap("/media/ghssvythiri/10C63D64C63D4AEC/asif/sqlite_working_aug_16/Resources/img/exit.jpg", wx.BITMAP_TYPE_ANY))
        self.label_1 = wx.StaticText(self.panel_1, wx.ID_ANY, _("Name"))
        self.label_2 = wx.StaticText(self.panel_1, wx.ID_ANY, _("UID"))
        self.label_3 = wx.StaticText(self.panel_1, wx.ID_ANY, _("Gender"))
        self.text_ctrl_2 = wx.TextCtrl(self.panel_1, wx.ID_ANY, "")
        self.text_ctrl_3 = wx.TextCtrl(self.panel_1, wx.ID_ANY, "")
        self.combo_box_16 = wx.ComboBox(self.panel_1, wx.ID_ANY, choices=[], style=wx.CB_DROPDOWN)
        self.label_4 = wx.StaticText(self.panel_1, wx.ID_ANY, _("Date of Birth"))
        self.label_5 = wx.StaticText(self.panel_1, wx.ID_ANY, _("Category"))
        self.label_6 = wx.StaticText(self.panel_1, wx.ID_ANY, _("Reigion"))
        self.text_ctrl_4 = wx.TextCtrl(self.panel_1, wx.ID_ANY, "")
        self.text_ctrl_5 = wx.TextCtrl(self.panel_1, wx.ID_ANY, "")
        self.text_ctrl_6 = wx.TextCtrl(self.panel_1, wx.ID_ANY, "")
        self.label_7 = wx.StaticText(self.panel_1, wx.ID_ANY, _("Caste"))
        self.label_8 = wx.StaticText(self.panel_1, wx.ID_ANY, _("First Language"))
        self.label_9 = wx.StaticText(self.panel_1, wx.ID_ANY, _("Father"))
        self.text_ctrl_7 = wx.TextCtrl(self.panel_1, wx.ID_ANY, "")
        self.text_ctrl_8 = wx.TextCtrl(self.panel_1, wx.ID_ANY, "")
        self.text_ctrl_9 = wx.TextCtrl(self.panel_1, wx.ID_ANY, "")
        self.label_10 = wx.StaticText(self.panel_1, wx.ID_ANY, _("Mother"))
        self.label_11 = wx.StaticText(self.panel_1, wx.ID_ANY, _("Mobile"))
        self.label_12 = wx.StaticText(self.panel_1, wx.ID_ANY, _("Email"))
        self.text_ctrl_10 = wx.TextCtrl(self.panel_1, wx.ID_ANY, "")
        self.text_ctrl_11 = wx.TextCtrl(self.panel_1, wx.ID_ANY, "")
        self.text_ctrl_12 = wx.TextCtrl(self.panel_1, wx.ID_ANY, "")
        self.hyperlink_1 = wx.HyperlinkCtrl(self.panel_1, wx.ID_ANY, "", "")
        self.hyperlink_2 = wx.HyperlinkCtrl(self.panel_1, wx.ID_ANY, "", "")
        self.hyperlink_3 = wx.HyperlinkCtrl(self.panel_1, wx.ID_ANY, "", "")
        self.static_line_2 = wx.StaticLine(self.panel_1, wx.ID_ANY)
        self.button_3 = wx.Button(self.panel_1, wx.ID_ANY, _("Delete"))
        self.button_2 = wx.Button(self.panel_1, wx.ID_ANY, _("Close"))
        self.button_4 = wx.Button(self.panel_1, wx.ID_ANY, _("Save"))

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_BUTTON, self.on_search, self.bitmap_button_2)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: student_profie.__set_properties
        self.SetTitle(_("frame_1"))
        self.combo_box_13.SetMinSize((200, 35))
        self.combo_box_14.SetMinSize((200, 35))
        self.combo_box_15.SetMinSize((200, 35))
        self.button_1.SetMinSize((110, 40))
        self.text_ctrl_1.SetMinSize((123, 35))
        self.bitmap_button_2.SetMinSize((50, 50))
        self.static_line_1.SetMinSize((800, 4))
        self.bitmap_button_1.SetMinSize((120, 120))
        self.label_1.SetFont(wx.Font(12, wx.DEFAULT, wx.ITALIC, wx.BOLD, 0, ""))
        self.label_2.SetFont(wx.Font(12, wx.DEFAULT, wx.ITALIC, wx.BOLD, 0, ""))
        self.label_3.SetFont(wx.Font(12, wx.DEFAULT, wx.ITALIC, wx.BOLD, 0, ""))
        self.text_ctrl_2.SetMinSize((300, 35))
        self.text_ctrl_3.SetMinSize((300, 35))
        self.combo_box_16.SetMinSize((100, 35))
        self.label_4.SetFont(wx.Font(12, wx.DEFAULT, wx.ITALIC, wx.BOLD, 0, ""))
        self.label_5.SetFont(wx.Font(12, wx.DEFAULT, wx.ITALIC, wx.BOLD, 0, ""))
        self.label_6.SetFont(wx.Font(12, wx.DEFAULT, wx.ITALIC, wx.BOLD, 0, ""))
        self.text_ctrl_4.SetMinSize((300, 35))
        self.text_ctrl_5.SetMinSize((300, 35))
        self.text_ctrl_6.SetMinSize((300, 35))
        self.label_7.SetFont(wx.Font(12, wx.DEFAULT, wx.ITALIC, wx.BOLD, 0, ""))
        self.label_8.SetFont(wx.Font(12, wx.DEFAULT, wx.ITALIC, wx.BOLD, 0, ""))
        self.label_9.SetFont(wx.Font(12, wx.DEFAULT, wx.ITALIC, wx.BOLD, 0, ""))
        self.text_ctrl_7.SetMinSize((300, 35))
        self.text_ctrl_8.SetMinSize((300, 35))
        self.text_ctrl_9.SetMinSize((300, 35))
        self.label_10.SetFont(wx.Font(12, wx.DEFAULT, wx.ITALIC, wx.BOLD, 0, ""))
        self.label_11.SetFont(wx.Font(12, wx.DEFAULT, wx.ITALIC, wx.BOLD, 0, ""))
        self.label_12.SetFont(wx.Font(12, wx.DEFAULT, wx.ITALIC, wx.BOLD, 0, ""))
        self.text_ctrl_10.SetMinSize((300, 35))
        self.text_ctrl_11.SetMinSize((300, 35))
        self.text_ctrl_12.SetMinSize((300, 35))
        self.static_line_2.SetMinSize((1130, 10))
        self.button_3.SetMinSize((120, 45))
        self.button_2.SetMinSize((120, 45))
        self.button_4.SetMinSize((120, 45))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: student_profie.__do_layout
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        sizer_2 = wx.BoxSizer(wx.VERTICAL)
        sizer_3 = wx.BoxSizer(wx.HORIZONTAL)
        grid_sizer_1 = wx.FlexGridSizer(9, 3, 10, 10)
        sizer_4 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_5 = wx.BoxSizer(wx.VERTICAL)
        grid_sizer_3 = wx.GridSizer(1, 2, 0, 0)
        sizer_6 = wx.BoxSizer(wx.HORIZONTAL)
        grid_sizer_2 = wx.GridSizer(1, 3, 10, 10)
        grid_sizer_2.Add(self.combo_box_13, 0, 0, 0)
        grid_sizer_2.Add(self.combo_box_14, 0, 0, 0)
        grid_sizer_2.Add(self.combo_box_15, 0, 0, 0)
        sizer_5.Add(grid_sizer_2, 1, wx.ALL | wx.EXPAND, 10)
        grid_sizer_3.Add(self.button_1, 0, wx.LEFT | wx.ALIGN_CENTER_VERTICAL, 20)
        sizer_6.Add(self.text_ctrl_1, 0, wx.LEFT | wx.ALIGN_CENTER_VERTICAL, 12)
        sizer_6.Add(self.bitmap_button_2, 0, wx.LEFT | wx.ALIGN_RIGHT | wx.ALIGN_CENTER_VERTICAL, 15)
        grid_sizer_3.Add(sizer_6, 1, wx.EXPAND, 0)
        sizer_5.Add(grid_sizer_3, 1, wx.EXPAND, 0)
        sizer_5.Add(self.static_line_1, 0, wx.EXPAND, 0)
        sizer_4.Add(sizer_5, 2, wx.EXPAND, 0)
        sizer_4.Add(self.bitmap_button_1, 0, wx.RIGHT | wx.TOP, 15)
        sizer_2.Add(sizer_4, 1, wx.EXPAND, 0)
        grid_sizer_1.Add(self.label_1, 0, wx.LEFT | wx.EXPAND, 10)
        grid_sizer_1.Add(self.label_2, 0, wx.LEFT | wx.EXPAND, 10)
        grid_sizer_1.Add(self.label_3, 0, wx.LEFT | wx.EXPAND, 10)
        grid_sizer_1.Add(self.text_ctrl_2, 0, 0, 0)
        grid_sizer_1.Add(self.text_ctrl_3, 0, 0, 0)
        grid_sizer_1.Add(self.combo_box_16, 0, 0, 0)
        grid_sizer_1.Add(self.label_4, 0, wx.LEFT | wx.EXPAND, 10)
        grid_sizer_1.Add(self.label_5, 0, wx.LEFT | wx.EXPAND, 10)
        grid_sizer_1.Add(self.label_6, 0, wx.LEFT | wx.EXPAND, 10)
        grid_sizer_1.Add(self.text_ctrl_4, 0, 0, 0)
        grid_sizer_1.Add(self.text_ctrl_5, 0, 0, 0)
        grid_sizer_1.Add(self.text_ctrl_6, 0, 0, 0)
        grid_sizer_1.Add(self.label_7, 0, wx.LEFT | wx.EXPAND, 10)
        grid_sizer_1.Add(self.label_8, 0, wx.LEFT | wx.EXPAND, 10)
        grid_sizer_1.Add(self.label_9, 0, wx.LEFT | wx.EXPAND, 10)
        grid_sizer_1.Add(self.text_ctrl_7, 0, 0, 0)
        grid_sizer_1.Add(self.text_ctrl_8, 0, 0, 0)
        grid_sizer_1.Add(self.text_ctrl_9, 0, 0, 0)
        grid_sizer_1.Add(self.label_10, 0, wx.LEFT | wx.EXPAND, 10)
        grid_sizer_1.Add(self.label_11, 0, wx.LEFT | wx.EXPAND, 10)
        grid_sizer_1.Add(self.label_12, 0, wx.LEFT | wx.EXPAND, 10)
        grid_sizer_1.Add(self.text_ctrl_10, 0, 0, 0)
        grid_sizer_1.Add(self.text_ctrl_11, 0, 0, 0)
        grid_sizer_1.Add(self.text_ctrl_12, 0, 0, 0)
        grid_sizer_1.Add(self.hyperlink_1, 0, 0, 0)
        grid_sizer_1.Add(self.hyperlink_2, 0, 0, 0)
        grid_sizer_1.Add(self.hyperlink_3, 0, 0, 0)
        grid_sizer_1.AddGrowableRow(1)
        grid_sizer_1.AddGrowableRow(3)
        grid_sizer_1.AddGrowableRow(5)
        grid_sizer_1.AddGrowableCol(0)
        grid_sizer_1.AddGrowableCol(1)
        grid_sizer_1.AddGrowableCol(2)
        sizer_2.Add(grid_sizer_1, 3, wx.ALL | wx.EXPAND | wx.ALIGN_CENTER_HORIZONTAL | wx.ALIGN_CENTER_VERTICAL | wx.SHAPED, 10)
        sizer_2.Add(self.static_line_2, 0, wx.ALL | wx.EXPAND, 10)
        sizer_3.Add(self.button_3, 0, wx.RIGHT, 40)
        sizer_3.Add(self.button_2, 0, wx.RIGHT | wx.ALIGN_RIGHT | wx.ALIGN_CENTER_HORIZONTAL, 40)
        sizer_3.Add(self.button_4, 0, wx.RIGHT, 40)
        sizer_2.Add(sizer_3, 1, wx.ALIGN_CENTER_HORIZONTAL | wx.ALIGN_CENTER_VERTICAL, 0)
        self.panel_1.SetSizer(sizer_2)
        sizer_1.Add(self.panel_1, 1, wx.EXPAND, 2)
        self.SetSizer(sizer_1)
        sizer_1.Fit(self)
        self.Layout()
        # end wxGlade

    def on_search(self, event):  # wxGlade: student_profie.<event_handler>
        print "Event handler 'on_search' not implemented!"
        event.Skip()

# end of class student_profie
if __name__ == "__main__":
    gettext.install("app") # replace with the appropriate catalog name

    app = wx.PySimpleApp(0)
    wx.InitAllImageHandlers()
    frame_1 = student_profie(None, wx.ID_ANY, "")
    app.SetTopWindow(frame_1)
    frame_1.Show()
    app.MainLoop()